language: cpp
compiler: gcc
env:
    global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
        - secure: "Drn8lpBITl8cc/5+SFlmhQ1dj19xh5MEQXtPz+KozlqxvX9iz1TkmS7tCwDlYYOa3FMY0jBWiBO31nRlpWM/QZccOwzIGRNezdinOYtu9DsvIGiagnQyccJ+PwJkoZYDUo764JNs3IsfFuT41r262svEc3vTzIVoaDo07dgHulUTSd3LPcdC/vH2uAmiUUdqNswMevMrAVA94McWBu085GDYQ5oPFbfk2rDbif9xKcEuFwTibBNVoSi1spiALoAM9FpnH2Jtu6uShlO7yKVWqZAolYf9fgYDBUr5Pd67uidJf4bDA9Hf7bzoAx1T7LlGbo26NBMaOGaOV2rYB0k1+yk96fWcYFXA60ndr/YDqKmiEeUaA53lhQ4+JUI0KRGmdjR0WXHKypsuNY2hgETaiY6OV1y0wrS+OVhd4t4f2reLThjGpyIddpkLWMd5RClf9MWMxe/4AOFxaLObWEswE4db9goJSbW2my+EkoHYJTDwumrGEOdun3M7h3w004w8+OqtiyUxA27UTbnPempdBUJfbhEWJtk3KNrOO4USIg4tAXuYZNCRqYjcdG+eiSGF2SOGIfCiJNUSKiXaEJq9wBcDL1w7Qs31C0QxUIgOdta/sJeFFe4rveh6fzoorU18QyYAGyvfAtHMcQBeVDP8rPKbQduxGZcieIFu/inlcDo="
    matrix:
        - PROTOBUF_VERSION=2.6.0

install:
    - echo | sudo apt-add-repository ppa:boost-latest/ppa
    - sudo apt-get update
    - sudo apt-get install libboost-dev
    - wget https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protobuf-$PROTOBUF_VERSION.tar.gz
    - tar xf protobuf-$PROTOBUF_VERSION.tar.gz
    - ( cd protobuf-$PROTOBUF_VERSION && ./configure && make -j4 && sudo make install)
    - git clone https://github.com/google/snappy
    - ( cd snappy && sh ./autogen.sh && ./configure && make -j2 && sudo make install && sudo ldconfig )
    - sudo apt-get install zlib1g-dev
    - git clone https://github.com/baidu/sofa-pbrpc ./thirdparty/sofa-pbrpc
    - ( cd thirdparty/sofa-pbrpc && make -j4 && make install);
    - wget https://github.com/gflags/gflags/archive/v2.1.2.tar.gz
    - tar xf v2.1.2.tar.gz
    - ( cd gflags-2.1.2 && cmake -DGFLAGS_NAMESPACE=google && make -j4 && sudo make install )
    - git clone https://github.com/baidu/common
    - ( cd common && make -j4 && make install)
    - wget --no-check-certificate https://googletest.googlecode.com/files/gtest-1.7.0.zip
    - unzip gtest-1.7.0.zip
    - ( cd gtest-1.7.0 && ./configure --disable-shared --with-pic && make -j4 && sudo cp -a lib/.libs/* /usr/lib && sudo cp -a include/gtest /usr/include )

    - wget http://download.savannah.gnu.org/releases/libunwind/libunwind-0.99-beta.tar.gz
    - tar zxvf libunwind-0.99-beta.tar.gz
    - ( cd libunwind-0.99-beta && ./configure CFLAGS=-U_FORTIFY_SOURCE --with-pic && make -j4 && sudo make install )

    - wget https://googledrive.com/host/0B6NtGsLhIcf7MWxMMF9JdTN3UVk/gperftools-2.2.1.tar.gz
    - tar zxvf gperftools-2.2.1.tar.gz
    - ( cd gperftools-2.2.1 && ./configure --with-pic && make -j4 && sudo make install && sudo ldconfig )



before_script:
    - echo 'SNAPPY_PATH=./thirdparty/snappy' > depends.mk
    - echo 'PROTOBUF_PATH=./thirdparty/protobuf' >> depends.mk
    - echo 'PROTOC=protoc' >> depends.mk
    - echo 'PBRPC_PATH=./thirdparty/sofa-pbrpc/output' >> depends.mk
    - echo 'TCMALLOC_PATH=./thirdparty' >> depends.mk
    - echo 'COMMON_PATH=./common/output' >> depends.mk

addons:
   coverity_scan:
       project:
           name: "myawan/bfs"
       notification_email: 185829549@qq.com
       build_command_prepend: "rm -rf output "
       build_command: "make -j4"
       branch_pattern: master

script: make -j4 && make test

